tunnel: 344e646f-5867-47ad-88dd-1ee169051622
credentials-file: /home/pi/.cloudflared/344e646f-5867-47ad-88dd-1ee169051622.json
ingress:
  - hostname: ha.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: ha.highcarlsagan.dev
  - hostname: pihole.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: pihole.highcarlsagan.dev
  - hostname: files.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: files.highcarlsagan.dev
  - hostname: passive.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: passive.highcarlsagan.dev
  - hostname: torrent.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: torrent.highcarlsagan.dev
  - hostname: status.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: status.highcarlsagan.dev

  - hostname: torrent.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: torrent.highcarlsagan.dev

  - hostname: docs.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: docs.highcarlsagan.dev

  - hostname: auth.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: auth.highcarlsagan.dev
  - hostname: resume.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: resume.highcarlsagan.dev
  - hostname: highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: highcarlsagan.dev
  - hostname: career-dashboard.highcarlsagan.dev
    service: https://localhost:443
    originRequest:
      noTLSVerify: true
      originServerName: career-dashboard.highcarlsagan.dev
  - service: http_status:404
